name: tests unitaires
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - name: Set up Python for Demo
       uses: actions/setup-python@v5
     - name: Install pytest
       run: pip install pytest
     - name: Run tests
       run: pytest test.py
     - run: echo "Nom branche: ${{ github.ref }}"
     - run: echo "OS": ${{ runner.os }}"
